
from typing import List, Dict, Tuple
import pandas as pd
from .common import barcode_to_ecomm_sku, validate_catalog_input

CATALOG_HEADERS: List[str] = [
  "Entity Identifier",
  "SKU Code",
  "Product Name",
  "Category Code",
  "Brand Code",
  "Product Subtitle",
  "Tax Applicable",
  "TaxOrHSN Code",
  "Product Description",
  "Article Description",
  "Article Code",
  "Article Type",
  "Tags Keyword",
  "Meta Title",
  "Meta Keyword",
  "Meta Description",
  "Location Group",
  "Vendor",
  "Is Active(Y/N)",
  "Is Publish(Y/N)",
  "Is customizable? (Y/N)",
  "Is 'New Arrival'",
  "Is Try at Store",
  "Is Try at Home",
  "Is Try On",
  "Is Price on Request",
  "Is Free Shipping?",
  "Product Net weight",
  "Product Net weight Unit",
  "Length",
  "Item Display Width",
  "Item Display Height",
  "Unit of LWH Dimension",
  "Min Quantity allowed in shopping cart",
  "Max Quantity allowed in shopping cart",
  "Delivery Type",
  "Store Code",
  "Is Gift Wrap",
  "Is inscription",
  "Is Pick Up at store",
  "Is EMI available",
  "Product Video",
  "PDP Image 1",
  "PDP Image 2",
  "PDP Image 3",
  "PDP Image 4",
  "PDP Image 5",
  "PDP Image 6",
  "PDP Image 7",
  "PDP Image 8",
  "PDP Image 9",
  "PDP Image 10",
  "PDP Image 11",
  "PDP Image 12",
  "PDP Image 13",
  "PDP Image 14",
  "PDP Image 15",
  "PLP Preview Image 1 ",
  "PLP Preview Image 2",
  "PLP Preview Image 3",
  "Collection",
  "HighJewellery Flag ",
  "Parent Theme",
  "Child Theme",
  "Segment",
  "Gender",
  "Certitificate Codes",
  "Jewel Type",
  "Product Gross Weight",
  "Product Gross Weight Unit",
  "Item Diameter",
  "Item Diameter Units",
  "Bracelet Length",
  "Ring Size",
  "Bangle Sizes",
  "Purity",
  "Polish Type",
  "Screw Type",
  "Setting Type",
  "Finish",
  "Style or Season or Occasion",
  "Metal Type",
  "Metal Name",
  "Metal Color",
  "Is 'Trendy Fashion'",
  "Pendant Loop Type",
  "Hook Type",
  "Bangle Shape",
  "Pattern",
  "Rows",
  "Attribute 1",
  "Attribute 2",
  "Attribute 3",
  "Attribute 4",
  "Attribute 5",
  "Attribute 6",
  "Attribute 7",
  "Attribute 8",
  "Attribute 9",
  "Attribute_10",
  "Product Highlights",
  "pieces",
  "Pieces UOM",
  "Is Returnable",
  "Is Cancellable"
]
CATALOG_TEMPLATE_ROWS: List[Dict[str, str]] = [
  {
    "Entity Identifier": "CR_entityIdentifier",
    "SKU Code": "CR_SKUCode",
    "Product Name": "CR_ProductName",
    "Category Code": "CR_CategoryCode",
    "Brand Code": "CR_BrandCode",
    "Product Subtitle": "CR_ProductTitle",
    "Tax Applicable": "CR_ShowPriceTaxIncl",
    "TaxOrHSN Code": "CR_TaxCode",
    "Product Description": "CR_ProductDesc",
    "Article Description": "CR_ArticleDesc",
    "Article Code": "CR_ArticleCode",
    "Article Type": "CR_ProductType",
    "Tags Keyword": "CR_Tags",
    "Meta Title": "CR_MetaTitle",
    "Meta Keyword": "CR_MetaKeyword",
    "Meta Description": "CR_MetaDescription",
    "Location Group": "CR_LocationGroup",
    "Vendor": "CR_SupplierCode",
    "Is Active(Y/N)": "CR_IsActive",
    "Is Publish(Y/N)": "CR_IsPublish",
    "Is customizable? (Y/N)": "CR_IsCustomizable",
    "Is 'New Arrival'": "CR_IsNewArrival",
    "Is Try at Store": "CR_Ex-BoolFlag1",
    "Is Try at Home": "CR_Ex-BoolFlag2",
    "Is Try On": "CR_Ex-BoolFlag3",
    "Is Price on Request": "CR_Ex-BoolFlag4",
    "Is Free Shipping?": "CR_IsFreeShipping",
    "Product Net weight": "VARIANT_Weight",
    "Product Net weight Unit": "VARIANT_WeightUnit",
    "Length": "VARIANT_ItemLength",
    "Item Display Width": "VARIANT_ItemWidth",
    "Item Display Height": "VARIANT_ItemHeight",
    "Unit of LWH Dimension": "VARIANT_LWH-Unit",
    "Min Quantity allowed in shopping cart": "CR_MinPurchaseQuantity",
    "Max Quantity allowed in shopping cart": "CR_MaxPurchaseQuantity",
    "Delivery Type": "CR_DeliveryType",
    "Store Code": "CR_StoreCode",
    "Is Gift Wrap": "CR_Gift-Wrap",
    "Is inscription": "CR_IsAlterable",
    "Is Pick Up at store": "CR_ClickAndCollect",
    "Is EMI available": "CR_EmiAvailable",
    "Product Video": "CR_Video",
    "PDP Image 1": "CR_IMG-PDP_1",
    "PDP Image 2": "CR_IMG-PDP_2",
    "PDP Image 3": "CR_IMG-PDP_3",
    "PDP Image 4": "CR_IMG-PDP_4",
    "PDP Image 5": "CR_IMG-PDP_5",
    "PDP Image 6": "CR_IMG-PDP_6",
    "PDP Image 7": "CR_IMG-PDP_7",
    "PDP Image 8": "CR_IMG-PDP_8",
    "PDP Image 9": "CR_IMG-PDP_9",
    "PDP Image 10": "CR_IMG-PDP_10",
    "PDP Image 11": "CR_IMG-PDP_11",
    "PDP Image 12": "CR_IMG-PDP_12",
    "PDP Image 13": "CR_IMG-PDP_13",
    "PDP Image 14": "CR_IMG-PDP_14",
    "PDP Image 15": "CR_IMG-PDP_15",
    "PLP Preview Image 1 ": "CR_IMG-PLP_1",
    "PLP Preview Image 2": "CR_IMG-PLP_2",
    "PLP Preview Image 3": "CR_IMG-PLP_3",
    "Collection": "ATTR_Collection",
    "HighJewellery Flag ": "ATTR_HighJewelleryFlag",
    "Parent Theme": "ATTR_Parent-Theme",
    "Child Theme": "ATTR_Child-Theme",
    "Segment": "ATTR_Segment",
    "Gender": "ATTR_Gender",
    "Certitificate Codes": "ATTR_Certificate-Codes",
    "Jewel Type": "VARIANT_JewelType",
    "Product Gross Weight": "VARIANT_ProductGrossWeight",
    "Product Gross Weight Unit": "VARIANT_ProductGrossWeightUnit",
    "Item Diameter": "VARIANT_ItemDiameter",
    "Item Diameter Units": "VARIANT_ItemDiameterUnits",
    "Bracelet Length": "ATTR_Bracelet-Length",
    "Ring Size": "VARIANT_Ring-Size",
    "Bangle Sizes": "VARIANT_Bangle-Size",
    "Purity": "VARIANT_Purity",
    "Polish Type": "VARIANT_Polish-Type",
    "Screw Type": "VARIANT_Screw-Type",
    "Setting Type": "ATTR_Setting-Type",
    "Finish": "ATTR_Finish",
    "Style or Season or Occasion": "ATTR_Style-Season-Occasion",
    "Metal Type": "ATTR_Metal-Type",
    "Metal Name": "ATTR_Metal-Name",
    "Metal Color": "ATTR_Metal-Color",
    "Is 'Trendy Fashion'": "ATTR_Trendy-Fashion",
    "Pendant Loop Type": "VARIANT_Pendant-Loop-Type",
    "Hook Type": "VARIANT_Hook-Type",
    "Bangle Shape": "VARIANT_Bangle-Shape",
    "Pattern": "ATTR_Pattern-Chains",
    "Rows": "ATTR_Rows-Chains",
    "Attribute 1": "ATTR_Attribute-1",
    "Attribute 2": "ATTR_Attribute-2",
    "Attribute 3": "ATTR_Attribute-3",
    "Attribute 4": "ATTR_Attribute-4",
    "Attribute 5": "ATTR_Attribute-5",
    "Attribute 6": "ATTR_Attribute-6",
    "Attribute 7": "ATTR_Attribute-7",
    "Attribute 8": "ATTR_Attribute-8",
    "Attribute 9": "ATTR_Attribute-9",
    "Attribute_10": "ATTR_Attribute-10",
    "Product Highlights": "ATTR_ProductHighlights",
    "pieces": "ATTR_pieces",
    "Pieces UOM": "VARIANT_UOM",
    "Is Returnable": "CR_RETURNABLE",
    "Is Cancellable": "CR_CANCELLABLE"
  },
  {
    "Entity Identifier": "Entity Identifier",
    "SKU Code": "Unique SKU/Variant Code",
    "Product Name": "Name of Product",
    "Category Code": "CategoryCode",
    "Brand Code": "BrandCode",
    "Product Subtitle": "Title of product",
    "Tax Applicable": "Whether to show price inclusive of Tax",
    "TaxOrHSN Code": "HSN code is a 6-digit uniform code that classifies 5000+ products and is accepted worldwide.",
    "Product Description": "Decription of product",
    "Article Description": "Article Description",
    "Article Code": "Article Code of the product (for accessories article code is the SKU code)",
    "Article Type": "Article Type",
    "Tags Keyword": "Comma separated multiple values",
    "Meta Title": "Meta Title of product",
    "Meta Keyword": "Meta Keyword of product",
    "Meta Description": "Meta Description of product",
    "Location Group": "LocationGroup",
    "Vendor": "Unique Vendor Code",
    "Is Active(Y/N)": "Whether Product is active?",
    "Is Publish(Y/N)": "Product is Published",
    "Is customizable? (Y/N)": "Cstomization possible or not",
    "Is 'New Arrival'": "Is Product is a New Arrival?",
    "Is Try at Store": " Try at Store",
    "Is Try at Home": "Try at Home",
    "Is Try On": "Try On",
    "Is Price on Request": "Is Price on Request",
    "Is Free Shipping?": "Is Free Shipping",
    "Product Net weight": "Weight of product",
    "Product Net weight Unit": "Unit weight of product",
    "Length": "Item Length",
    "Item Display Width": "Item Width",
    "Item Display Height": "Item Height",
    "Unit of LWH Dimension": "Unit of LWH Dimension",
    "Min Quantity allowed in shopping cart": "Min Purchase Quantity ",
    "Max Quantity allowed in shopping cart": "Max Purchase Quantity of product",
    "Delivery Type": "Type of Delivery(Standard/Express)",
    "Store Code": "StoreCode",
    "Is Gift Wrap": "Gift Wrap",
    "Is inscription": "Is inscription",
    "Is Pick Up at store": "Is Pick Up at store",
    "Is EMI available": "EMI available",
    "Product Video": "Product Video",
    "PDP Image 1": "PDP Image",
    "PDP Image 2": "PDP Image2",
    "PDP Image 3": "PDP Image3",
    "PDP Image 4": "PDP Image4",
    "PDP Image 5": "PDP Image5",
    "PDP Image 6": "PDP Image 6",
    "PDP Image 7": "PDP Image 7",
    "PDP Image 8": "PDP Image 8",
    "PDP Image 9": "PDP Image 9",
    "PDP Image 10": "PDP Image 10",
    "PDP Image 11": "PDP Image 11",
    "PDP Image 12": "PDP Image 12",
    "PDP Image 13": "PDP Image 13",
    "PDP Image 14": "PDP Image 14",
    "PDP Image 15": "PDP Image 15",
    "PLP Preview Image 1 ": "PLP Preview Image 1 ",
    "PLP Preview Image 2": "PLP Preview Image 2",
    "PLP Preview Image 3": "PLP Preview Image 3",
    "Collection": "Collection",
    "HighJewellery Flag ": "High Jewellery",
    "Parent Theme": "Parent Theme",
    "Child Theme": "Child Theme",
    "Segment": "Segment of the product",
    "Gender": "Gender",
    "Certitificate Codes": "Certitificate Codes",
    "Jewel Type": "Jewel Type",
    "Product Gross Weight": "Product Gross Weight",
    "Product Gross Weight Unit": "Product Gross Weight Unit",
    "Item Diameter": "ItemDiameter",
    "Item Diameter Units": "Item Diameter Units",
    "Bracelet Length": "Bracelet Length",
    "Ring Size": "Ring Size",
    "Bangle Sizes": "Bangle Size",
    "Purity": "Purity",
    "Polish Type": "Polish Type",
    "Screw Type": "Screw Type",
    "Setting Type": "Setting Type",
    "Finish": "Finish",
    "Style or Season or Occasion": "Style or Season or Occasion",
    "Metal Type": "Metal Type",
    "Metal Name": "Metal Name",
    "Metal Color": "Metal Color",
    "Is 'Trendy Fashion'": "Trendy Fashion",
    "Pendant Loop Type": "Pendant Loop Type",
    "Hook Type": "Hook Type",
    "Bangle Shape": "Bangle Shape",
    "Pattern": "Patter",
    "Rows": "Rows",
    "Attribute 1": "Attribute 1",
    "Attribute 2": "Attribute 2",
    "Attribute 3": "Attribute 3",
    "Attribute 4": "Attribute 4",
    "Attribute 5": "Attribute 5",
    "Attribute 6": "Attribute 6",
    "Attribute 7": "Attribute 7",
    "Attribute 8": "Attribute 8",
    "Attribute 9": "Attribute 9",
    "Attribute_10": "Attribute 10",
    "Product Highlights": "Product Highlights: Multiple highlights separated by '@@' ",
    "pieces": "Pieces",
    "Pieces UOM": "Pieces UOM",
    "Is Returnable": "Is Returnable",
    "Is Cancellable": "Is Cancellable"
  },
  {
    "Entity Identifier": "OPTION",
    "SKU Code": "TextField",
    "Product Name": "TextField",
    "Category Code": "OPTION",
    "Brand Code": "OPTION",
    "Product Subtitle": "TextField",
    "Tax Applicable": "OPTION",
    "TaxOrHSN Code": "TextField",
    "Product Description": "TextField",
    "Article Description": "TextField",
    "Article Code": "TextField",
    "Article Type": "OPTION",
    "Tags Keyword": "TextField",
    "Meta Title": "TextField",
    "Meta Keyword": "TextField",
    "Meta Description": "TextField",
    "Location Group": "OPTION",
    "Vendor": "TextField",
    "Is Active(Y/N)": "Boolean",
    "Is Publish(Y/N)": "Boolean",
    "Is customizable? (Y/N)": "Boolean",
    "Is 'New Arrival'": "Boolean",
    "Is Try at Store": "Boolean",
    "Is Try at Home": "Boolean",
    "Is Try On": "Boolean",
    "Is Price on Request": "Boolean",
    "Is Free Shipping?": "Boolean",
    "Product Net weight": "INTEGER",
    "Product Net weight Unit": "OPTION",
    "Length": "OPTION",
    "Item Display Width": "TextField",
    "Item Display Height": "TextField",
    "Unit of LWH Dimension": "OPTION",
    "Min Quantity allowed in shopping cart": "INTEGER",
    "Max Quantity allowed in shopping cart": "INTEGER",
    "Delivery Type": "OPTION",
    "Store Code": "OPTION",
    "Is Gift Wrap": "Boolean",
    "Is inscription": "Boolean",
    "Is Pick Up at store": "Boolean",
    "Is EMI available": "Boolean",
    "Product Video": "TextField",
    "PDP Image 1": "TextField",
    "PDP Image 2": "TextField",
    "PDP Image 3": "TextField",
    "PDP Image 4": "TextField",
    "PDP Image 5": "TextField",
    "PDP Image 6": "TextField",
    "PDP Image 7": "TextField",
    "PDP Image 8": "TextField",
    "PDP Image 9": "TextField",
    "PDP Image 10": "TextField",
    "PDP Image 11": "TextField",
    "PDP Image 12": "TextField",
    "PDP Image 13": "TextField",
    "PDP Image 14": "TextField",
    "PDP Image 15": "TextField",
    "PLP Preview Image 1 ": "TextField",
    "PLP Preview Image 2": "TextField",
    "PLP Preview Image 3": "TextField",
    "Collection": "OPTION",
    "HighJewellery Flag ": "Boolean",
    "Parent Theme": "OPTION",
    "Child Theme": "OPTION",
    "Segment": "OPTION",
    "Gender": "OPTION",
    "Certitificate Codes": "OPTION",
    "Jewel Type": "OPTION",
    "Product Gross Weight": "INTEGER",
    "Product Gross Weight Unit": "OPTION",
    "Item Diameter": "TextField",
    "Item Diameter Units": "OPTION",
    "Bracelet Length": "INTEGER",
    "Ring Size": "OPTION",
    "Bangle Sizes": "OPTION",
    "Purity": "OPTION",
    "Polish Type": "OPTION",
    "Screw Type": "OPTION",
    "Setting Type": "OPTION",
    "Finish": "TextField",
    "Style or Season or Occasion": "TextField",
    "Metal Type": "TextField",
    "Metal Name": "TextField",
    "Metal Color": "TextField",
    "Is 'Trendy Fashion'": "Boolean",
    "Pendant Loop Type": "OPTION",
    "Hook Type": "OPTION",
    "Bangle Shape": "OPTION",
    "Pattern": "TextField",
    "Rows": "INTEGER",
    "Attribute 1": "TextField",
    "Attribute 2": "TextField",
    "Attribute 3": "TextField",
    "Attribute 4": "TextField",
    "Attribute 5": "TextField",
    "Attribute 6": "TextField",
    "Attribute 7": "TextField",
    "Attribute 8": "TextField",
    "Attribute 9": "TextField",
    "Attribute_10": "TextField",
    "Product Highlights": "TextField",
    "pieces": "TextField",
    "Pieces UOM": "OPTION",
    "Is Returnable": "Boolean",
    "Is Cancellable": "Boolean"
  },
  {
    "Entity Identifier": "20",
    "SKU Code": "20",
    "Product Name": "100",
    "Category Code": "40",
    "Brand Code": "20",
    "Product Subtitle": "100",
    "Tax Applicable": "10",
    "TaxOrHSN Code": "30",
    "Product Description": "500",
    "Article Description": "100",
    "Article Code": "50",
    "Article Type": "100",
    "Tags Keyword": "500",
    "Meta Title": "30",
    "Meta Keyword": "500",
    "Meta Description": "100",
    "Location Group": "50",
    "Vendor": "20",
    "Is Active(Y/N)": "20",
    "Is Publish(Y/N)": "20",
    "Is customizable? (Y/N)": "10",
    "Is 'New Arrival'": "20",
    "Is Try at Store": "20",
    "Is Try at Home": "20",
    "Is Try On": "20",
    "Is Price on Request": "20",
    "Is Free Shipping?": "20",
    "Product Net weight": "20",
    "Product Net weight Unit": "10",
    "Length": "10",
    "Item Display Width": "20",
    "Item Display Height": "20",
    "Unit of LWH Dimension": "20",
    "Min Quantity allowed in shopping cart": "10",
    "Max Quantity allowed in shopping cart": "10",
    "Delivery Type": "20",
    "Store Code": "20",
    "Is Gift Wrap": "20",
    "Is inscription": "20",
    "Is Pick Up at store": "20",
    "Is EMI available": "20",
    "Product Video": "200",
    "PDP Image 1": "100",
    "PDP Image 2": "100",
    "PDP Image 3": "100",
    "PDP Image 4": "100",
    "PDP Image 5": "100",
    "PDP Image 6": "100",
    "PDP Image 7": "100",
    "PDP Image 8": "100",
    "PDP Image 9": "100",
    "PDP Image 10": "100",
    "PDP Image 11": "100",
    "PDP Image 12": "100",
    "PDP Image 13": "100",
    "PDP Image 14": "100",
    "PDP Image 15": "100",
    "PLP Preview Image 1 ": "100",
    "PLP Preview Image 2": "100",
    "PLP Preview Image 3": "100",
    "Collection": "100",
    "HighJewellery Flag ": "20",
    "Parent Theme": "20",
    "Child Theme": "20",
    "Segment": "5",
    "Gender": "20",
    "Certitificate Codes": "200",
    "Jewel Type": "20",
    "Product Gross Weight": "20",
    "Product Gross Weight Unit": "10",
    "Item Diameter": "20",
    "Item Diameter Units": "20",
    "Bracelet Length": "10",
    "Ring Size": "10",
    "Bangle Sizes": "10",
    "Purity": "20",
    "Polish Type": "20",
    "Screw Type": "20",
    "Setting Type": "50",
    "Finish": "50",
    "Style or Season or Occasion": "20",
    "Metal Type": "20",
    "Metal Name": "20",
    "Metal Color": "40",
    "Is 'Trendy Fashion'": "20",
    "Pendant Loop Type": "20",
    "Hook Type": "20",
    "Bangle Shape": "20",
    "Pattern": "50",
    "Rows": "10",
    "Attribute 1": "100",
    "Attribute 2": "100",
    "Attribute 3": "100",
    "Attribute 4": "100",
    "Attribute 5": "100",
    "Attribute 6": "100",
    "Attribute 7": "100",
    "Attribute 8": "100",
    "Attribute 9": "100",
    "Attribute_10": "100",
    "Product Highlights": "10000",
    "pieces": "20",
    "Pieces UOM": "20",
    "Is Returnable": "20",
    "Is Cancellable": "20"
  }
]

ERP_TO_CATALOG_MAP: Dict[str, str] = {
  "Entity Identifier": "Entity",
  "SKU Code": "Bar Code",
  "Product Name": "Article Description",
  "Product Subtitle": "Article Description",
  "Tax Applicable": "Tax Applicable",
  "TaxOrHSN Code": "HSN Code",
  "Article Description": "Article Description",
  "Article Code": "Article Number",
  "Article Type": "Article Type",
  "Vendor": "Vendor",
  "Product Net weight": "Net Metal Weight",
  "Product Net weight Unit": "Net Metal Weight Units",
  "Product Gross Weight": "Gross Item Weight",
  "Product Gross Weight Unit": "Gross Item Weight Unit",
  "Collection": "Collection",
  "Purity": "Purity",
  "Metal Type": "Metal Type",
  "Metal Name": "Metal Name",
  "Gender": "Gender Description",
  "Parent Theme": "Parent Theme",
  "Child Theme": "Child Theme",
  "Segment": "Segment",
  "Jewel Type": "Jewel Type",
  "Polish Type": "Polish Type Description",
  "Setting Type": "Setting Type Description",
  "Bangle Size": "Bangle Size",
  "Bangle Shape": "Bangle Shape",
  "Hook Type": "Hook Type Description",
  "UOM": "UOM",
  "Pieces": "Pieces"
}

def transform_catalog(input_df: pd.DataFrame) -> Tuple[pd.DataFrame, pd.DataFrame]:
    df, err = validate_catalog_input(input_df.copy())
    out = pd.DataFrame(columns=CATALOG_HEADERS)
    meta = pd.DataFrame(CATALOG_TEMPLATE_ROWS)
    out = pd.concat([meta, out], ignore_index=True)

    mapped = pd.DataFrame(columns=CATALOG_HEADERS)
    for col in CATALOG_HEADERS:
        if col in ERP_TO_CATALOG_MAP:
            src = ERP_TO_CATALOG_MAP[col]
            if src in df.columns:
                mapped[col] = df[src]
            else:
                mapped[col] = ""
        else:
            mapped[col] = ""

    # Special handling for SKU Code (use CKC_00 + 8-digit Bar Code if available)
    if 'SKU Code' in mapped.columns and 'Bar Code' in df.columns:
        mapped['SKU Code'] = df['Bar Code'].apply(barcode_to_ecomm_sku)

    # Default flags
    for fld in ['Is Active(Y/N)','Is Publish(Y/N)']:
        if fld in mapped.columns:
            mapped[fld] = 'Y'

    # Return/Cancellable defaults if present
    for fld in ['Is Returnable','Is Cancellable']:
        if fld in mapped.columns and (mapped[fld] == "").all():
            mapped[fld] = 'Y'

    final = pd.concat([out, mapped], ignore_index=True)
    return final, err
